app/db/models/position.py
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy import String

from app.db import Base 

class Position(Base):
    __tablename__ = "positions"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(20))

app/db/models/post.py
from datetime import datetime

from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import String, ForeignKey
from sqlalchemy.types import TEXT, TIMESTAMP
from sqlalchemy.sql import func

from app.db import Base, User


class Post(Base):
    __tablename__ = "posts"

    id: Mapped[int] = mapped_column(primary_key=True)
    title: Mapped[str] = mapped_column(String(200))
    text: Mapped[str] = mapped_column(TEXT())
    public_date: Mapped[datetime] = mapped_column(TIMESTAMP(), server_default=func.now())
    user_id: Mapped[int] = mapped_column(ForeignKey(User.id))
    user: Mapped[User] = relationship()



app/db/models/user.py
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import String, ForeignKey

from app.db import Base, Position

class User(Base):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(primary_key=True)
    first_name: Mapped[str] = mapped_column(String(50))
    last_name: Mapped[str] = mapped_column(String(50))
    position_id: Mapped[int] = mapped_column(ForeignKey(Position.id))
    position: Mapped[Position] = relationship()

app/__init__.py
from flask import Flask
from app.db import create_db
from app.routes import position_route, user_route, post_route
from app.data.password import ADMIN_PASS


app = Flask(__name__)
app.secret_key = ADMIN_PASS
app.register_blueprint(position_route)
app.register_blueprint(user_route)
app.register_blueprint(post_route)



def main():
    create_db()
    app.run(debug=True)

app/db/__init__.py
from .base import Session, Base, create_db
from .models.position import Position
from .models.user import User
from .models.post import Post

app/routes/__init__.py
from .positions import position_route
from .user import user_route
from .post import post_route

app/routes/positions.py
from flask import Blueprint, render_template, request, redirect

from app.db import Session, Position
from app.data.password import ADMIN_PASS


position_route = Blueprint("positions", __name__, url_prefix="/positions/")


@position_route.get("/")
@position_route.post("/")
def add_position():
    msg = ""
    block = False
    if request.method == "POST":
        name = request.form.get("name")

        password = request.form.get("password")
        if password == ADMIN_PASS:
            with Session() as session:
                position = Position(name=name)
                session.add(position)
                session.commit()
                msg = "Посада успішно додана"
        else:
            block = True

    return render_template("position.html", block=block, msg=msg)

app/routes/post.py
from flask import Blueprint, request, render_template, redirect, url_for, flash

from app.db import Session, User, Post
from app.data.password import ADMIN_PASS

post_route = Blueprint("posts", __name__)


@post_route.get("/posts/")
@post_route.post("/posts/")
def add_post():
    with Session() as session:
        if request.method == "POST":
            title = request.form.get("title")
            text = request.form.get("text")
            user_id = request.form.get("user_id")
            post = Post(title=title, text=text, user_id=user_id)

            if request.form.get("password") == ADMIN_PASS:
                session.add(post)
                session.commit()
                flash("Статтю успішно додано")
            else:
                flash("Невірний пароль")


        users = session.query(User).all()
        return render_template("add_post.html", users=users)
        



@post_route.get("/post/<int:id>/")
def get_post(id):
    with Session() as session:
        post = session.query(Post).where(Post.id == id).first()
        return render_template("post.html", post=post)
    

@post_route.get("/")
def index():
    with Session() as session:
        posts = session.query(Post).all()
        return render_template  ("index.html", posts=posts)
    

@post_route.get("/post/del/<int:id>/")
def del_post(id):
    with Session() as session:
        post = session.query(Post).where(Post.id == id).first()
        session.delete(post)
        session.commit()
        return redirect(url_for("posts.index"))
    


@post_route.get("/post/edit/<int:id>/")
@post_route.post("/post/edit/<int:id>/")
def edit_post(id):
    with Session() as session:
        post = session.query(Post).where(Post.id == id).first()
        if request.method == "POST":
            title = request.form.get("title")
            text = request.form.get("text")

            post.title = title
            post.text = text
            session.commit()
            return redirect(url_for("post.index"))
        
        return render_template("add_post.html", post=post)

app/routes/user.py
from flask import Blueprint, render_template, request

from app.db import Base, Session, User, Position
from app.data.password import ADMIN_PASS


user_route = Blueprint("users", __name__, url_prefix="/users/")


@user_route.get("/")
@user_route.post("/")
def add_user():
    block = False
    msg = ""
    with Session() as session:
        if request.method == "POST":
            first_name = request.form.get("first_name")
            last_name = request.form.get("last_name")
            position_id = request.form.get("position_id")

            if request.form.get("password") == ADMIN_PASS:
                user = User(first_name=first_name, last_name=last_name, position_id=position_id)
                session.add(user)
                session.commit()
                msg = "Користувача успішно додано"
            else:
                block = True

        positions = session.query(Position).all()
        context = {
            "positions": positions,
            "block": block,
            "msg": msg
        }
        return render_template("user.html", **context)

app/templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>{% block title %} FlaskBlog {% endblock title %}</title>
</head>
<body class="p-5 bg-primary-subtle">
    {% include "_navigation.html" %}
    {% block content %}
    {% endblock content %}
    <div class="container text-center">
        <div class="row">
            <div class="col">
                {% block left_content %}
                {% endblock left_content %}
            </div>
            <div class="col">
                {% block center_content %}
                {% endblock center_content %}
            </div>
            <div class="col">
                {% block right_content %}
                {% endblock right_content %}
            </div>
        </div>
    </div>
</body>
</html>

app/templates/_navigation.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{ url_for('posts.index') }}">Головна сторінка</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{ url_for('posts.add_post') }}">Додати статтю</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('users.add_user') }}">Додати користувача</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('positions.add_position') }}">Додати посаду</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

app/templates/add_post.html
{% extends "_base.html" %}

{% block center_content %}
    {% if post %}
        <form action="{{ url_for('posts.edit_post', id=post.id) }}" method="post">
    {% else %}
        <form action="{{ url_for('posts.add_post') }}" method="post">
    {% endif %}

    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Назва статті</label>

        {% if post %}
            <input type="text" class="form-control" id="exampleInputEmail1" name="title" value="{{ request.form.title or post.title }}">
        {% else %}
            <input type="text" class="form-control" id="exampleInputEmail1" name="title" value="{{ request.form.title }}">
        {% endif %}

    </div>
        <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Стаття</label>

        {% if post %}
            <textarea type="text" class="form-control" id="exampleInputEmail1" name="text">{{ request.form.text or post.text }}</textarea>
        {% else %}
            <textarea type="text" class="form-control" id="exampleInputEmail1" name="text">{{ request.form.text }}</textarea>
        {% endif %}

    </div>
    {% if not post %}
        <select name="user_id" class="form-control">
            {% for user in users %}
                <option value="{{ user.id }}">{{ user.last_name }} {{ user.first_name }}</option>
            {% endfor %}
        </select>
    {% endif %}
    <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Пароль адміністратора</label>
        <input type="password" class="form-control" id="exampleInputPassword1" name="password">
    </div>
    <button type="submit" class="btn btn-primary">Додати</button>
    </form>

    {% with messages = get_flashed_messages() %}
        {% for msg in messages %}
            <h5 class="btn btn-info">{{ msg }}</h5>
        {% endfor %}
    {% endwith %}
{% endblock center_content %}

app/templates/index.html
{% extends "_base.html" %}

{% block content %}
{% block title %}
    FlaskBlog forever
{% endblock title %}
{% endblock content %}

{% block center_content %}
    {% for post in posts %}
        <div class="card">
        <div class="card-body">
            <h5 class="card-title">Назва статті</h5>
            <p class="card-text"><em>Автор: </em>{{ post.user.last_name }} {{ post.user.first_name }}</p>
            <a href="{{ url_for('posts.get_post', id=post.id) }}" class="btn btn-primary">Прочитати статтю</a>
        </div>
        </div>
    {% endfor %}
{% endblock center_content %}

app/templates/position.html
{% extends "_base.html" %}

{% block center_content %}
<form action="{{ url_for('positions.add_position') }}" method="post">
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Назва посади</label>
    <input type="text" class="form-control" id="exampleInputEmail1" name="name">
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Пароль адміністратора</label>
    <input type="password" class="form-control" id="exampleInputPassword1" name="password">
  </div>
  <button type="submit" class="btn btn-primary">Додати</button>
  <h3>{{ msg }}</h3>
</form>

{% if block %}
    <img src="https://http.cat/401">
{% endif %}
{% endblock center_content %}

app/templates/post.html
{% extends "_base.html" %}

{% block content %}

    <div class="card-body">
        <h5 class="card-title">{{ post.title }}</h5>
        <p class="card-text">{{ post.text }}</p>
        <a href="{{ url_for('posts.edit_post', id=post.id) }}" class="btn btn-info">Редагувати статтю</a>
        <a href="{{ url_for('posts.del_post', id=post.id) }}" class="btn btn-danger">Видалити статтю</a>
    </div>

{% endblock content %}

app/templates/user.html
{% extends "_base.html" %}

{% block center_content %}
<form action="{{ url_for('users.add_user') }}" method="post">
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Прізвище</label>
    <input type="text" class="form-control" id="exampleInputEmail1" name="last_name">
  </div>
    <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Ім'я</label>
    <input type="text" class="form-control" id="exampleInputEmail1" name="first_name">
  </div>
  <select name="position_id" class="form-control">
    {% for position in positions %}
        <option value="{{ position.id }}">{{ position.name }}</option>
    {% endfor %}
  </select>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Пароль адміністратора</label>
    <input type="password" class="form-control" id="exampleInputPassword1" name="password">
  </div>
  <button type="submit" class="btn btn-primary">Додати</button>
  <h3>{{ msg }}</h3>
</form>

{% if block %}
    <img src="https://http.cat/401">
{% endif %}
{% endblock center_content %}